/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as MedicineInformationRouteImport } from './routes/medicine-information'
import { Route as MembersRouteImport } from './routes/members'
import { Route as PathologicalTestsRouteImport } from './routes/pathological-tests'
import { Route as QuizGamesRouteImport } from './routes/quiz-games'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TeamLoginRouteImport } from './routes/team-login'
import { Route as AuthenticatedCertificateRouteImport } from './routes/_authenticated/certificate'
import { Route as AuthenticatedEventsRouteImport } from './routes/_authenticated/events'
import { Route as AuthenticatedFeesRouteImport } from './routes/_authenticated/fees'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedTrainingLogsRouteImport } from './routes/_authenticated/training-logs'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicineInformationRoute = MedicineInformationRouteImport.update({
  id: '/medicine-information',
  path: '/medicine-information',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const PathologicalTestsRoute = PathologicalTestsRouteImport.update({
  id: '/pathological-tests',
  path: '/pathological-tests',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizGamesRoute = QuizGamesRouteImport.update({
  id: '/quiz-games',
  path: '/quiz-games',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamLoginRoute = TeamLoginRouteImport.update({
  id: '/team-login',
  path: '/team-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCertificateRoute =
  AuthenticatedCertificateRouteImport.update({
    id: '/certificate',
    path: '/certificate',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEventsRoute = AuthenticatedEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFeesRoute = AuthenticatedFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTrainingLogsRoute =
  AuthenticatedTrainingLogsRouteImport.update({
    id: '/training-logs',
    path: '/training-logs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/jobs': typeof JobsRoute
  '/medicine-information': typeof MedicineInformationRoute
  '/members': typeof MembersRoute
  '/pathological-tests': typeof PathologicalTestsRoute
  '/quiz-games': typeof QuizGamesRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team-login': typeof TeamLoginRoute
  '/certificate': typeof AuthenticatedCertificateRoute
  '/events': typeof AuthenticatedEventsRoute
  '/fees': typeof AuthenticatedFeesRoute
  '/team': typeof AuthenticatedTeamRoute
  '/training-logs': typeof AuthenticatedTrainingLogsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/jobs': typeof JobsRoute
  '/medicine-information': typeof MedicineInformationRoute
  '/members': typeof MembersRoute
  '/pathological-tests': typeof PathologicalTestsRoute
  '/quiz-games': typeof QuizGamesRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team-login': typeof TeamLoginRoute
  '/certificate': typeof AuthenticatedCertificateRoute
  '/events': typeof AuthenticatedEventsRoute
  '/fees': typeof AuthenticatedFeesRoute
  '/team': typeof AuthenticatedTeamRoute
  '/training-logs': typeof AuthenticatedTrainingLogsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/jobs': typeof JobsRoute
  '/medicine-information': typeof MedicineInformationRoute
  '/members': typeof MembersRoute
  '/pathological-tests': typeof PathologicalTestsRoute
  '/quiz-games': typeof QuizGamesRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team-login': typeof TeamLoginRoute
  '/_authenticated/certificate': typeof AuthenticatedCertificateRoute
  '/_authenticated/events': typeof AuthenticatedEventsRoute
  '/_authenticated/fees': typeof AuthenticatedFeesRoute
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/_authenticated/training-logs': typeof AuthenticatedTrainingLogsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/gallery'
    | '/jobs'
    | '/medicine-information'
    | '/members'
    | '/pathological-tests'
    | '/quiz-games'
    | '/register'
    | '/reset-password'
    | '/sitemap.xml'
    | '/team-login'
    | '/certificate'
    | '/events'
    | '/fees'
    | '/team'
    | '/training-logs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/gallery'
    | '/jobs'
    | '/medicine-information'
    | '/members'
    | '/pathological-tests'
    | '/quiz-games'
    | '/register'
    | '/reset-password'
    | '/sitemap.xml'
    | '/team-login'
    | '/certificate'
    | '/events'
    | '/fees'
    | '/team'
    | '/training-logs'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/gallery'
    | '/jobs'
    | '/medicine-information'
    | '/members'
    | '/pathological-tests'
    | '/quiz-games'
    | '/register'
    | '/reset-password'
    | '/sitemap.xml'
    | '/team-login'
    | '/_authenticated/certificate'
    | '/_authenticated/events'
    | '/_authenticated/fees'
    | '/_authenticated/team'
    | '/_authenticated/training-logs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  JobsRoute: typeof JobsRoute
  MedicineInformationRoute: typeof MedicineInformationRoute
  MembersRoute: typeof MembersRoute
  PathologicalTestsRoute: typeof PathologicalTestsRoute
  QuizGamesRoute: typeof QuizGamesRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TeamLoginRoute: typeof TeamLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medicine-information': {
      id: '/medicine-information'
      path: '/medicine-information'
      fullPath: '/medicine-information'
      preLoaderRoute: typeof MedicineInformationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pathological-tests': {
      id: '/pathological-tests'
      path: '/pathological-tests'
      fullPath: '/pathological-tests'
      preLoaderRoute: typeof PathologicalTestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz-games': {
      id: '/quiz-games'
      path: '/quiz-games'
      fullPath: '/quiz-games'
      preLoaderRoute: typeof QuizGamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team-login': {
      id: '/team-login'
      path: '/team-login'
      fullPath: '/team-login'
      preLoaderRoute: typeof TeamLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/certificate': {
      id: '/_authenticated/certificate'
      path: '/certificate'
      fullPath: '/certificate'
      preLoaderRoute: typeof AuthenticatedCertificateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/events': {
      id: '/_authenticated/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AuthenticatedEventsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fees': {
      id: '/_authenticated/fees'
      path: '/fees'
      fullPath: '/fees'
      preLoaderRoute: typeof AuthenticatedFeesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/training-logs': {
      id: '/_authenticated/training-logs'
      path: '/training-logs'
      fullPath: '/training-logs'
      preLoaderRoute: typeof AuthenticatedTrainingLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCertificateRoute: typeof AuthenticatedCertificateRoute
  AuthenticatedEventsRoute: typeof AuthenticatedEventsRoute
  AuthenticatedFeesRoute: typeof AuthenticatedFeesRoute
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
  AuthenticatedTrainingLogsRoute: typeof AuthenticatedTrainingLogsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCertificateRoute: AuthenticatedCertificateRoute,
  AuthenticatedEventsRoute: AuthenticatedEventsRoute,
  AuthenticatedFeesRoute: AuthenticatedFeesRoute,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
  AuthenticatedTrainingLogsRoute: AuthenticatedTrainingLogsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  JobsRoute: JobsRoute,
  MedicineInformationRoute: MedicineInformationRoute,
  MembersRoute: MembersRoute,
  PathologicalTestsRoute: PathologicalTestsRoute,
  QuizGamesRoute: QuizGamesRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TeamLoginRoute: TeamLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
